apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: prod
stringData:
  POSTGRES_DB: appdb
  POSTGRES_USER: appuser
  POSTGRES_PASSWORD: password
  POSTGRES_HOST: postgres.prod.svc.cluster.local  
  POSTGRES_PORT: "5432"                           
  PGPASSWORD: password
