apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: xappdatabase-provider-role
rules:
  - apiGroups: ["batch"]
    resources: ["jobs", "jobs/status"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["pods", "pods/log"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: xappdatabase-provider-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: xappdatabase-provider-role
subjects:
  - kind: ServiceAccount
    name: provider-kubernetes-fd54bbc7f877
    namespace: crossplane-system